package model;

public class Time {

    // REMOVE TIME CLASS
    // HANDLE THE CHANGES IN THE CONTROLLER
    // WHEN THE USER ADVANCES ON DAY, CHECK CONTRACT, CREDITS ETC AND IF ANYTHING NEEDS UPDATING UPDATE.
    
}
